name: Pidgin Ipsum
title: null
description: Reference site about Pidgin Ipsum, as well as a random Pidsum snippets.
github_edit_link: https://github.com/koolamusic/pidgin.ipsum/edit/main/README.md
github:
  private: false
  is_user_page: true
  is_org_page: false
  name: koolamusic
  title: null
  description: Reference site about Pidgin Ipsum, as well as a random Pidsum snippets.
  url: https://github.com/koolamusic/pidgin.ipsum